### PR TITLE
43-training-program-detail

### LINKED ISSUE #43: Training Program Detail View
### Feature Description
Create a View, ViewModel and Method that will display the details of a specific Training Program and a List of Employees enrolled in that program.

1.

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Provide a Detail View for a Training Program that also lists the names of all attendees

## Resolves Issue Number
Resolves #43 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 43-training-program-detail
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. Navigate to localhost/TrainingProgram/Detail/1

## Impacted Files in Application
List general components of the application that this PR will affect:

* TrainingProgram/Detail view, viewmodel and controller

### CODE REVIEW

**Comment by daynewright** [comment]
LGTM!

**Comment by garrett-vangilder** [comment]
LGTM! IT WORKKKS 🌵

**Review by matthamil — APPROVED** [review]
LGTM 🌮

**Review by Anulfo — COMMENTED** [review]
LGTM

**Pull request merged**
