### PR TITLE
Db init

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
If no employees are in the database, on startup the Data/DbInitializer.cs file will generate dummy data for your database.

## Resolves Issue Number
#22 

## Deploy Notes

```sh
git pull --prune
rm -rf Migrations/
rm -f bangazon.db
git checkout db-init
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. See if your database has data on all tables

## Impacted Files in Application
List general components of the application that this PR will affect:

* Database
* Startup

### CODE REVIEW

**Review by matthamil — APPROVED** [review]
LGTM. Database populates properly.

**Comment by daynewright** [comment]
LGTM!

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
