### PR TITLE
34-training-program-index

### LINKED ISSUE #34: Training Program List Method
### Feature Description
Create a method on the `ProgramController` that returns a view of the different programs and how many attendees are in training.

1. On `ProgramController.cs` make an `IActionResult List` method.
2. `List` should:
    -Retrieve context an make an instance of it.
    -Then use the method `List` to retrieve the Program List and return the view
```
public async Task<IActionResult> List()
        {
            ProgramList.ForEach(CalculateTypeQuantities);
            var model = new ProgramList(context);
            model.Program = await context.Program.OrderBy(s => s.Name).ToListAsync();
            return View(model);
        }
```

    -Create the CalculateTypeQuantities method.

```
public void CalculateTypeQuantities(ProductType productType)
        {
            int quantity = context.Product.Count(p => p.ProductTypeId == productType.ProductTypeId && p.IsActive == true);
            productType.Quantity = quantity;
```
### Related Issues/PRs
#30

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Provide a view for the user that will display a list of all Training Program names and descriptions.

## Resolves Issue Number
Resolves #34 

## Deploy Notes

```sh
git pull --prune
git checkout 34-training-program-index
dotnet run
```

## Steps to Test or Reproduce

1.  Navigate to localhost/TrainingProgram/Index
1. Confirm that a list of Training Programs appears

## Impacted Files in Application

* Views/TrainingProgram/Index
* ViewModels/TrainingProgram/TrainingProgramIndex
* Controllers/TrainingProgramController

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
LGTM besides the reference thing, which will be fixed shortly 👍

**Comment by MattKraatz** [comment]
I still need to display a number of employees in each department. Stay tuned.

**Comment by matthamil** [comment]
TrainingPrograms View Model needs documentation

**Review by daynewright — APPROVED** [review]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by matthamil** [comment]
Can we add a default route to `localhost:5000/TrainingProgram` so the user doesn't have to type `localhost:5000/TrainingProgram/Index`? @MattKraatz Otherwise LGTM

**Review by Anulfo — COMMENTED** [review]
LGTM

**Pull request merged**
