### PR TITLE
67-department-list-bug : fixed department bugs

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
* Sorting Departments alphabetically by name
* Allow users to create a department with no employees
* On successful creation of a department, route the user to the detail page for that department

## Resolves Issue Number
Resolves bugs #67 and #70 

## Deploy Notes

```sh
git pull --prune
git checkout 67-department-list-bug
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. See Description section above

## Impacted Files in Application
List general components of the application that this PR will affect:

* Controllers/DepartmentsController

### CODE REVIEW

**Comment by matthamil** [comment]
The Employee dropdown on Add a Department defaults to "Select a Category"

Other than that, LGTM

image

**Review by matthamil — APPROVED** [review]
:taco:

**Comment by daynewright** [comment]
LGTM (after changes above)

**Comment by MattKraatz** [comment]
Changes made!

**Comment by garrett-vangilder** [comment]
LGTM

**Pull request merged**
