### PR TITLE
Added README

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation. Just read the README.

## Description
A README to help users download and run the project.

## Deploy Notes

```sh
Go to https://github.com/TeamCharles/workforce-management/blob/37-readme/README.md
Read it.
```

## Steps to Test or Reproduce

1. Read https://github.com/TeamCharles/workforce-management/blob/37-readme/README.md

## Impacted Files in Application

* README

### CODE REVIEW

**Comment by daynewright** [comment]
LGTM!

**Review by daynewright — APPROVED** [review]
👍

**Comment by MattKraatz** [comment]
Nice work

**Comment by garrett-vangilder** [comment]
LGTM

**Pull request merged**
