### PR TITLE
71-computerListBugFix :: Sorts the computer list by Serial Number

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

**[ X ]** I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Serial numbers are now sorted in the Computer List view at `localhost:5000/Computer`

## Resolves Issue Number

https://github.com/TeamCharles/workforce-management/issues/71

## Deploy Notes

```sh
git pull --prune
git checkout 71-computerListBugFix
dotnet run
```

## Steps to Test or Reproduce

1. Navigate to `localhost:5000`

1. Enjoy the sorted list by Serial Number

1. Add a new Computer with a new SN

1. Continue enjoying the sorted list

## Impacted Files in Application
List general components of the application that this PR will affect:

* ViewModels/Computer/ComputerIndex.cs

## Resources

For information about how `SortedDictionary<KeyValuePair<TKey, TValue>>` works, here are some helpful links I used:

[SortedDictionary<KeyValuePair<TKey, TValue>> Documentation](https://msdn.microsoft.com/en-us/library/f7fta44c(v=vs.110).aspx)

[IComparer<T> Documentation](https://msdn.microsoft.com/en-us/library/8ehhxeaf(v=vs.110).aspx)

[String.CompareTo Method](https://msdn.microsoft.com/en-us/library/fkw3h78a(v=vs.110).aspx)

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by daynewright** [comment]
LGTM

**Review by MattKraatz — APPROVED** [review]
LGTM

**Pull request merged**
