### PR TITLE
12-addNewComputerForm - New Computer Form

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
User can now navigate to the `/Computer` route and see a button that says "Add a Computer". The "Add a Computer" button redirects the user to a form with field validation. The user can create a new computer, and the app will reroute back to the computer list view.

## Resolves Issue Number

https://github.com/TeamCharles/workforce-management/issues/12

## Deploy Notes

```sh
git pull --prune
git checkout 12-addNewComputerForm
dotnet run
```

## Steps to Test or Reproduce

1. Navigate to `localhost:5000/Computer`

1. Click the "Add a New Computer" button

1. Attempt to create a new computer without filling out every field

1. Fill out the form properly and hit "Add new Computer"

1. Find your computer in the list on the `/Computer` page

## Impacted Files in Application

* Controllers/ComputerController.cs

* ViewModels/Computer/ComputerAdd.cs

* Views/Computer/ComputerAdd.cshtml

* wwwroot/js/site.js

### CODE REVIEW

**Comment by matthamil** [comment]
Ready for review @TeamCharles/team

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Review by daynewright — DISMISSED** [review]
We need to check if the serial number already exists in the database.  Currently you can add another computer with the same serial number.

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by garrett-vangilder** [comment]
looks dope to me

**Pull request merged**
