### PR TITLE
20-create-models : Initialize Database

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Create all models per the ERD.

## Resolves Issue Number
#20 

## Deploy Notes

```sh
git pull --prune
git checkout "20-create-models"
dotnet restore
dotnet ef database update
dotnet run
```

## Steps to Test or Reproduce

1. Follow the commands above
1. Open the database file in SQLbrowser and make sure tables were created

## Impacted Files in Application

* Database

### CODE REVIEW

**Comment by daynewright** [comment]
LGTM! 👍

**Comment by matthamil** [comment]
LGTM :+1:

**Review by matthamil — APPROVED** [review]
:+1:

**Review by Anulfo — COMMENTED** [review]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Pull request merged**
