### PR TITLE
63-employee-detail - Employee Detail View

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Employee detail view now live :100:

## Resolves Issue Number

https://github.com/TeamCharles/workforce-management/issues/63

## Deploy Notes
```sh
git pull --prune
git checkout 63-employee-detail
dotnet run
```

## Steps to Test or Reproduce

1. Navigate to `localhost:5000/Employee/Detail/1`

1. Look at Carson's employee info

1. Find another employee

1. View their detail info page

## Impacted Files in Application

* Controllers/EmployeeController.cs

* ViewModels/Employee/EmployeeDetail.cs

* Views/Employee/Detail.cshtml

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Review by MattKraatz — APPROVED** [review]
:metal:

**Comment by daynewright** [comment]
Somebody give this guy a JOB!  NICE 💯 🚀   LGTM

**Review by Anulfo — COMMENTED** [review]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Pull request merged**
