### PR TITLE
14-employee-creation

### LINKED ISSUE #14: Employee Creation Form View
### Feature Description
Generate a boilerplate View and Controller method for the Employee/Add story.

1. Create a View at `Views/Employee/Add.cshtml`
1. View must contain a form with the following inputs:
   * First Name (text)
   * Last Name (text)
   * Department (select dropdown)
   * Computer (select dropdown)
   * Training Programs (multi-select) (optional)
1. View must have an `Add Employee` button that is disabled until all required fields contain values
   * Add two event listeners with JQuery
      1. Document Ready: check whether all fields contain values, otherwise disable button
      1. Input Change: if all fields have values, enable button, otherwise disable button
1. Add an `Add()` method to `Controllers/EmployeeController.cs` that returns a `View()`
1. Create a ViewModel to provide to the view, ViewModel must contain:
   * Employee
   * List<SelectItemElements> Departments
   * List<SelectItemElements> Available Computers
   * List<SelectItemElements> Training Programs
1. Load some dummy data into a ViewModel

### Related Issues/PRs
User Story #2

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Provide a form to the Employee/Add view that allows a user to create a new Employee. The Employee must be assigned a computer and a department, and may optionally be added to one or more training programs. On successful creation, you should be routed to a detail view for that newly created user.

## Resolves Issue Number
Resolves #14 and #19 

## Deploy Notes

```sh
git pull --prune
git checkout 14-employee-creation
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. Navigate to localhost/Employee/Add
1. Fill out the form
1. The "Add Employee" button should be disabled until all of the required fields are completed
1. You should only be able to select from unassigned Computers
1. Validation should work
1. After submitting the form, a new Employee record should be created in your database
1. If you selected any training programs, new Attendee records should be created

## Impacted Files in Application
List general components of the application that this PR will affect:

* Views/Employee/Add
* Controllers/EmployeeController
* ViewModels/Employee/EmployeeForm
* site.js

### CODE REVIEW

**Review by garrett-vangilder — COMMENTED** [review]
👍  Great job, thank you for the help with the int[] Good looking code.

**Review by garrett-vangilder — APPROVED** [review]

**Review by Anulfo — COMMENTED** [review]
LGTM

**Comment by matthamil** [comment]
The Computer dropdown on the `Add an Employee` page defaults to "Department" instead of "Computer"

LGTM

**Comment by daynewright** [comment]
LGTM!   I think we should remove the `Select a Program` option from the multi-select.

**Pull request merged**
