### PR TITLE
Update training programs

### PR DESCRIPTION
**Pull request by garrett-vangilder**
## Status
**READY/IN DEVELOPMENT**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[Z] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

It adds functionality!

## Resolves Issue Number

n/a
## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout update-training-program
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. 

## Impacted Files in Application
List general components of the application that this PR will affect:

* Most files

### CODE REVIEW

**Review by daynewright — APPROVED** [review]
💩 👜

**Review by MattKraatz — APPROVED** [review]
🎓

**Comment by garrett-vangilder** [comment]
🍟

**Comment by Anulfo** [comment]
LGTM

**Comment by daynewright** [comment]
🍟 :canada:

**Comment by MattKraatz** [comment]
🍔

**Comment by daynewright** [comment]
🎺

**Comment by Anulfo** [comment]
🎱

**Pull request merged**
