### PR TITLE
75-employeeListFullNameBugFix :: Fixed Employee List bugs

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Name column should display the Full Name and be sorted by Last Name. The Employee's name should be a hyperlink to the Details page for that Employee. Removed the Details button and column.

## Resolves Issue Number

https://github.com/TeamCharles/workforce-management/issues/66

## Deploy Notes

```sh
git pull --prune
git checkout 75-employeeListFullNameBugFix
dotnet run
```

## Steps to Test or Reproduce

1. Navigate to `localhost:5000/Employee`

1. Click an Employees name to ensure that the route works

## Impacted Files in Application

* Views/Employee/Index.cshtml

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Review by daynewright — APPROVED** [review]
LGTM!

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Pull request merged**
