### PR TITLE
added department controller/viewmodel/view

### PR DESCRIPTION
**Pull request by daynewright**
## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Adds a controller, view model and view for the departments.

## Resolves Issue Number
#23
## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 23-departments-controller
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1.  dotnet run
2. navigate to localhost:5000/department/index

## Impacted Files in Application
List general components of the application that this PR will affect:

* /Views/Department/Index.cshtml
* /ViewModels/Department/DepartmentIndex.cs
* /Controllers/DepartmentController.cs

### CODE REVIEW

**Review by MattKraatz — APPROVED** [review]
LGTM

**Comment by garrett-vangilder** [comment]
LGTM

**Comment by matthamil** [comment]
Check your documentation in `DepartmentIndex` viewmodel. Your property `DepartmentList` is not a constructor ;)

LGTM

**Review by Anulfo — COMMENTED** [review]
LGTM

**Pull request merged**
